const questions=[['客戶問：「簽完約，為什麼還要再見面？」',['先說明下一訪如何連回他的財務目標','直接約時間，見面再解釋'],'先交代流程與服務目的，建立共同理解。'],['客戶說有 100 萬可以投入，你下一步怎麼做？',['再確認期間、生活需求與緊急預備金','把 100 萬全部列為可用資源'],'初次回答需要二次確認；可用金額要以生活與承受能力為前提。'],['市場尚未符合下跌加碼條件，這一訪怎麼收尾？',['完成盤點並預告下一步，等待條件','為了讓見面有成果，立即投入'],'先說明規則與條件，避免為交易而交易。'],['客戶保障已符合需求，醫療險這一訪怎麼做？',['記錄健檢結果，定期檢視','依課堂預算比例再增加保費'],'依需求補強，完整就不補強。'],['客戶不想了解合作，你應該怎麼回應？',['理解原因、尊重意願，再確認服務需求','把拒絕視為必須反覆刺激的訊號'],'溝通線索用來確認理解，不能取代客戶自主決定。']];document.getElementById('questions').innerHTML=questions.map((q,i)=>`<article class="panel" style="margin-bottom:18px"><h3>${i+1}. ${q[0]}</h3>${q[1].map((a,j)=>`<label class="task"><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}<p id="feedback${i}"></p></article>`).join('');document.getElementById('grade').onclick=()=>{let score=0;questions.forEach((q,i)=>{let a=document.querySelector(`input[name=q${i}]:checked`);if(a?.value==='0')score++;document.getElementById('feedback'+i).textContent=(a?(a.value==='0'?'✓ 正確。':'再想一想。'):'尚未作答。')+q[2]});document.getElementById('score').textContent=`答對 ${score} / 5 題。`};const key='u-after-course-v1';let state={};try{state=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch(e){}function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch(e){document.getElementById('saveStatus').textContent='此瀏覽器無法儲存，請複製筆記保留。'}}function progress(){let n=document.querySelectorAll('.read:checked').length;document.getElementById('progress').value=n;document.getElementById('count').textContent=n+' / 5'}document.querySelectorAll('.read,.homework').forEach(el=>{el.checked=!!state[el.id];el.onchange=()=>{state[el.id]=el.checked;save();progress()}});let notes=document.getElementById('notes');notes.value=state.notes||'';notes.oninput=()=>{state.notes=notes.value;save()};progress();
// Journey navigation, practice tools and feedback.
const lessonNames=['延伸下一訪','下跌加碼','V 系列','醫療險補強','通路合作'];
document.querySelector('.side-links').innerHTML=lessonNames.map((n,i)=>`<a href="#s${i+1}" data-link="${i+1}"><small>0${i+1}</small>　${n}</a>`).join('');
function updateJourney(){let n=document.querySelectorAll('.read:checked').length;document.getElementById('sideCount').textContent=`${n} / 5 段完成`;document.getElementById('sideBar').style.width=n/5*100+'%';let next=[...document.querySelectorAll('.read')].find(e=>!e.checked);let target=next?'#s'+next.id.replace('read',''):'#quiz';document.getElementById('resume').href=target;document.getElementById('resume').innerHTML=n?`繼續${n===5?'情境測驗':'服務路線'} <span>↗</span>`:'開始服務路線 <span>↗</span>';document.getElementById('mobileResume').href=target;document.querySelectorAll('[data-link]').forEach(a=>a.classList.toggle('completed',document.getElementById('read'+a.dataset.link).checked));}
document.querySelectorAll('.read').forEach(e=>e.addEventListener('change',()=>{updateJourney();if(e.checked)toast('已儲存這一訪的學習進度')}));updateJourney();
let toastTimer;function toast(message){let el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('[data-link]').forEach(a=>{let active=a.dataset.link===e.target.dataset.step;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current')})}})},{rootMargin:'-15% 0px -55% 0px',threshold:0});document.querySelectorAll('.lesson-section').forEach(s=>observer.observe(s));
function scrollProgress(){let max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.scroll-meter i').style.width=(max>0?scrollY/max*100:0)+'%'}addEventListener('scroll',scrollProgress,{passive:true});scrollProgress();
document.querySelectorAll('.copy-script').forEach(button=>button.onclick=async()=>{const quote=button.closest('blockquote').cloneNode(true);quote.querySelector('.script-heading').remove();try{await navigator.clipboard.writeText(quote.textContent.trim());toast('話術已複製，可以換成你的語氣')}catch(e){toast('請選取下方話術，使用系統複製功能')}});
// Alternate answer positions so the exercise tests understanding.
document.querySelectorAll('#questions .panel').forEach((panel,i)=>{if(i%2===1){const labels=panel.querySelectorAll('label');panel.insertBefore(labels[1],labels[0])}});
document.getElementById('questions').addEventListener('change',()=>{let n=document.querySelectorAll('#questions input:checked').length;document.getElementById('answered').textContent=`${n} / 5 題已作答`});
document.getElementById('grade').addEventListener('click',()=>{questions.forEach((q,i)=>{let input=document.querySelector(`input[name=q${i}]:checked`);let feedback=document.getElementById('feedback'+i);feedback.className=input?.value==='0'?'correct':'incorrect'});let unanswered=questions.findIndex((q,i)=>!document.querySelector(`input[name=q${i}]:checked`));if(unanswered>=0){document.querySelector(`input[name=q${unanswered}]`).focus();toast('還有未作答的情境，已帶你回到第一題')}else{document.getElementById('score').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}});
document.getElementById('resetQuiz').onclick=()=>{document.querySelectorAll('#questions input').forEach(e=>e.checked=false);document.querySelectorAll('#questions p').forEach(e=>{e.textContent='';e.className=''});document.getElementById('score').textContent='';document.getElementById('answered').textContent='0 / 5 題已作答';document.querySelector('#questions input').focus();toast('測驗已重設，再練習一次')};
document.getElementById('exportNotes').onclick=()=>{let text='成交Ｕ之後｜我的下一訪計畫\n\n'+notes.value+'\n\n本週練習\n'+[...document.querySelectorAll('.homework')].map(e=>(e.checked?'✓ ':'□ ')+e.parentElement.textContent.trim()).join('\n');let url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));let a=document.createElement('a');a.href=url;a.download='我的下一訪計畫.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('下一訪計畫已下載')};
notes.addEventListener('input',()=>{if(document.getElementById('saveStatus').textContent.includes('無法'))return;document.getElementById('saveStatus').textContent='已自動儲存在此瀏覽器。'});

const visits=[
{title:'建立下一訪',goal:'讓客戶理解成交後流程，願意討論下一步。',say:'交代扣款、簽收與後續安排；每次見面討論一個策略。',gate:'客戶能說出自己的目標，以及下次見面的目的。',next:'確認作業時間，約資源盤點與策略說明。'},
{title:'確認可用資源',goal:'在生活與風險承受能力範圍內，盤點可用資金。',say:'確認資金可保留的期間，二次核對生活需求。',gate:'資金用途、預備金、風險與啟動條件已確認；未符合條件就等待。',next:'整理既有資源，準備同條件的方案比較。'},
{title:'評估 V 系列',goal:'看懂調整資源後，財務目標可能如何改變。',say:'用相同期間與投入比較，完整說明費用、波動及風險。',gate:'客戶理解假設與限制，並自主決定是否調整。',next:'確認成交後時間軸，接續保障安全檢視。'},
{title:'守住財務目標',goal:'減少事故發生時，被迫動用長期資產的壓力。',say:'先查既有保單可支付多少，再依需求與預算找缺口。',gate:'給付條件與缺口已核對，補強順序有共識；完整就不補強。',next:'約定保障檢視；有意願時，再了解合作。'},
{title:'了解合作選擇',goal:'在理解服務與自願的前提下，討論分享與合作。',say:'說明服務價值、資格、時間投入及報酬條件。',gate:'客戶清楚合作方式，也知道自己可以不參與。',next:'依意願約實際說明機會，保留後續服務安排。'}];
const tabs=document.getElementById('visitTabs');tabs.innerHTML=visits.map((v,i)=>`<button id="visitTab${i}" role="tab" aria-controls="visitPanel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-visit="${i}"><small>VISIT 0${i+1}</small>${lessonNames[i]}</button>`).join('');
function showVisit(i,focus=false){tabs.querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1});const v=visits[i];const panel=document.getElementById('visitPanel');panel.setAttribute('aria-labelledby','visitTab'+i);panel.innerHTML=`<span class="map-target">0${i+1} / 05 · 這一訪的任務</span><h3>${v.title}</h3><div class="map-grid"><div class="map-cell"><small>目的</small><p>${v.goal}</p></div><div class="map-cell"><small>關鍵說法</small><p>${v.say}</p></div><div class="map-cell"><small>完成條件</small><p>${v.gate}</p></div><div class="map-cell"><small>下一步</small><p>${v.next}</p></div></div><a href="#s${i+1}">進入這一訪的話術與細節 →</a>`;if(focus)document.getElementById('visitTab'+i).focus()}
tabs.addEventListener('click',e=>{const b=e.target.closest('button');if(b)showVisit(Number(b.dataset.visit))});tabs.addEventListener('keydown',e=>{let current=Number(e.target.closest('button')?.dataset.visit);if(!Number.isInteger(current))return;let next;if(e.key==='ArrowRight')next=(current+1)%5;if(e.key==='ArrowLeft')next=(current+4)%5;if(e.key==='Home')next=0;if(e.key==='End')next=4;if(next!==undefined){e.preventDefault();showVisit(next,true)}});showVisit(0);
const scenarios=[
['成交後邀約','「不是已經買好了嗎？怎麼還要約？」',['先約就對了，下次再跟你說。','先說明下一訪與他的目標有什麼關係。'],1,'客戶還沒理解目的，直接約時間容易造成壓力。先建立共識。','「這次成交完成後，我會確認後續流程。下一次，我想跟你整理可用資源，看看有沒有適合你的策略。你希望先了解哪一部分？」',1],
['資源二次確認','「我有 100 萬，全部可以用吧？」',['確認期間、用途、預備金與臨時支出。','資源越多越好，直接以 100 萬規劃。'],0,'先保留生活安全，再談策略；不能把帳戶餘額直接當成可投資金額。','「先不急著決定全部投入。這筆錢有沒有預定用途？如果遇到臨時支出，你還有其他預備金嗎？我們再確認你能接受的期間與波動。」',2],
['市場尚未下跌','「今天沒有下跌，那我們不就白見面了？」',['先投入一點，才有進度。','說明這一訪已完成的盤點與等待條件。'],1,'拜訪的成果可以是理解與準備，並不一定是交易。','「今天我們已確認可用資源與策略條件，這就是準備的進度。現在條件還沒符合，我們先等待；下一次再討論其他適合你的選擇。」',2],
['方案風險溝通','「所以換過去，就一定能提早五年？」',['強調示例已經算出來了。','釐清這是情境試算，並一起看風險。'],1,'把目標推演與保證區分清楚，才能建立可靠的共識。','「五年是這組假設下的試算，不是保證。我們要一起看投入、費用、波動和收益不如預期的情況，再決定你是否適合。」',3],
['保障預算有限','「我知道有缺口，但現在預算不夠。」',['依優先順序處理，保留後續檢視。','依固定比例補滿，其他以後再說。'],0,'接受真實預算限制，避免補強保障反而壓縮必要生活支出。','「我們先把缺口排優先順序，在你能負擔的範圍內討論。暫時無法處理的先記下來，後續收入或條件改變，再一起檢視。」',4],
['合作邀約','「我不想介紹朋友，也沒有時間參加。」',['持續刺激，直到他願意。','尊重意願，回到原本的服務安排。'],1,'理解與自主意願是合作的前提。拒絕合作不應影響原本服務。','「了解，你可以先不參與。我們依原來的財務與保障需求繼續服務；之後若你有興趣，再由你決定是否了解。」',5]];
const select=document.getElementById('scenario');select.innerHTML=scenarios.map((s,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · ${s[0]}</option>`).join('');function renderScenario(){const s=scenarios[Number(select.value)];document.getElementById('clientLine').textContent=s[1];document.getElementById('replyChoices').innerHTML=s[2].map((reply,i)=>`<button type="button" aria-pressed="false" data-reply="${i}">${String.fromCharCode(65+i)} · ${reply}</button>`).join('');document.getElementById('replyFeedback').replaceChildren()}select.onchange=renderScenario;renderScenario();document.getElementById('replyChoices').onclick=e=>{let b=e.target.closest('button');if(!b)return;let s=scenarios[Number(select.value)],correct=Number(b.dataset.reply)===s[3];document.querySelectorAll('[data-reply]').forEach(a=>a.setAttribute('aria-pressed',a===b));document.getElementById('replyFeedback').innerHTML=`<b>${correct?'✓ 這個回應能推進理解':'換個角度，再練習一次'}</b><p>${s[4]}</p><small>可以這樣接話</small><p class="model-reply">${s[5]}</p><a href="#s${s[6]}">回看這一訪 →</a>`};
